export const ROUTES = Object.freeze({
  MAIN: "/",
  REGISTER: "/register",
  LOGIN: "/login",
  PRODUCTS: "/products",
  PRODUCT_DETAILS: "/products/:id",
  CART: "/cart",
  ORDERS: "/orders",
  ORDER_DETAILS: "/orders/:id",
  SEARCH: "/search",
  PROFILE: "/profile",
  CHECKOUT: "/checkout",
  ADMIN: "/admin",
  ADMIN_ADD_PRODUCT: "/admin/products/add",
  GOOGLE_CALLBACK: "/oauth/callback",
});
